#!/usr/bin/env python3
"""Generate gaps/INDEX.md — a flat, fetchable listing of every gap.

Why this exists: a public LLM running training mode has no reliable way to LIST
the gaps/ directory. The GitHub contents API (.../contents/gaps) returns 403 to
anonymous, rate-limited clients, and github.com/tree HTML is robots-blocked. The
one primitive that reliably returns 200 is a raw.githubusercontent.com URL to a
specific FILE. So we maintain a single index FILE the prompt can fetch by its raw
URL, and this script (re)builds it from the gap files themselves.

INDEX.md is a DERIVED projection of files that already exist on main — it holds no
new knowledge, so gap-index.yml regenerates and commits it directly (it is not a
mediated content write). The gap files remain the source of truth.

Pure standard library. Run from the repo root: python3 gen_gap_index.py
"""

from __future__ import annotations

import glob
import os
import re

RAW_BASE = "https://raw.githubusercontent.com/Pappydapimp69/Collective/main/gaps"
GAP_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*\.md$")

_HEADER = re.compile(r"^#\s*Gap:\s*(.+)$")
_FIELD = re.compile(r"^-\s*\*\*(Type|Status):\*\*\s*(.+)$")


def _parse(path: str) -> dict[str, str]:
    gap = gtype = status = ""
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            s = line.strip()
            m = _HEADER.match(s)
            if m and not gap:
                gap = m.group(1).strip()
                continue
            m = _FIELD.match(s)
            if m:
                key, val = m.group(1).lower(), m.group(2).strip()
                if key == "type" and not gtype:
                    gtype = val.lower()
                elif key == "status" and not status:
                    status = val.lower()
    return {"gap": gap, "type": gtype, "status": status}


def build_index(gaps_dir: str = "gaps") -> str:
    names = sorted(
        os.path.basename(p)
        for p in glob.glob(os.path.join(gaps_dir, "*.md"))
        if GAP_SLUG_RE.match(os.path.basename(p))
    )
    lines = [
        "# Gap index",
        "",
        "Auto-generated by `gen_gap_index.py` (via `.github/workflows/gap-index.yml`).",
        "Do not edit by hand — edits are overwritten. The individual gap files are the",
        "source of truth; this is a flat listing so a training-mode session can find an",
        "existing gap without listing the directory (the contents API 403s anonymously).",
        "",
        f"{len(names)} gap(s). Each entry links the raw URL to open.",
        "",
    ]
    if not names:
        lines.append("_No gaps yet._")
    for name in names:
        meta = _parse(os.path.join(gaps_dir, name))
        lines.append(f"- **{name}** — type: {meta['type'] or '?'} · status: {meta['status'] or '?'}")
        if meta["gap"]:
            lines.append(f"  - {meta['gap']}")
        lines.append(f"  - {RAW_BASE}/{name}")
    return "\n".join(lines) + "\n"


def main() -> None:
    text = build_index()
    with open(os.path.join("gaps", "INDEX.md"), "w", encoding="utf-8") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
