#!/usr/bin/env python3
"""Generate AUTO_PROMPT_BUNDLED.md — the auto prompt with the snapshot EMBEDDED.

Consumer chatbots can't reliably fetch GitHub, so a fetch-based prompt keeps
failing at "read the snapshot." This bundles the current snapshot index (the
coverage map the trainer needs to find a real gap) directly into the prompt, so
a paste is fully self-contained — zero fetching required.

Derived from AUTO_PROMPT.md (single source for the prompt body) + snapshot/*/
index.md (single source for the coverage map). Regenerated by the export
workflow whenever the snapshot refreshes, so it never goes stale. Fails loudly
if an expected anchor is missing, so prompt edits can't silently desync it.

Run from the repo root: python3 gen_auto_prompt.py
Pure standard library.
"""

from __future__ import annotations

import os
import re

NODES = ["memory", "ideas", "tension", "creativity"]


def _require(condition: bool, msg: str) -> None:
    if not condition:
        raise SystemExit(f"gen_auto_prompt: {msg} — AUTO_PROMPT.md changed shape; update the generator.")


def _snapshot_block() -> str:
    parts = ["=== EMBEDDED SNAPSHOT (the brain's current coverage map — your gap comes from HERE) ==="]
    for node in NODES:
        path = os.path.join("snapshot", node, "index.md")
        _require(os.path.exists(path), f"missing {path}")
        lines = open(path, encoding="utf-8").read().splitlines()
        # drop the generated-at header line; keep the one-line-per-entry body
        body = [l for l in lines if l.strip() and not l.startswith("# collective index")]
        parts.append(f"\n--- {node} ({len(body)} entries) ---")
        parts.extend(body)
    return "\n".join(parts) + "\n"


def build_bundled() -> str:
    src = open("AUTO_PROMPT.md", encoding="utf-8").read()

    # strip the leading HTML comment header
    src = re.sub(r"^<!--.*?-->\n+", "", src, count=1, flags=re.DOTALL)

    # Replace the "READ THE SNAPSHOT FIRST … forks.)" paragraph (fetch-based)
    # with a bundled pointer to the embedded snapshot at the end of the prompt.
    read_re = re.compile(r"READ THE SNAPSHOT FIRST —.*?unresolved forks\.\)", re.DOTALL)
    _require(bool(read_re.search(src)), "could not find the READ THE SNAPSHOT FIRST block")
    bundled_intro = (
        "USE THE EMBEDDED SNAPSHOT — a gap must come from the brain's actual knowledge, "
        "never be invented from thin air. You do NOT need to fetch anything: the brain's "
        "current coverage map (one line per entry) is embedded at the END of this prompt. "
        "Read it there and find your gap in it. (The `tension` section is especially rich "
        "— its entries are literally open, unresolved forks.)"
    )
    src = read_re.sub(bundled_intro, src)

    # Fix step 1's fetch-or-paste aside — the snapshot is embedded now.
    aside_re = re.compile(
        r"The only thing you may pause for before this is getting the snapshot itself\s*"
        r"\(fetch it, or ask the user to paste it\) — never for which gap to pick\."
    )
    _require(bool(aside_re.search(src)), "could not find step 1's snapshot aside")
    src = aside_re.sub(
        "The snapshot is embedded at the end of this prompt — read it there; never pause "
        "for which gap to pick.",
        src,
    )

    header = (
        "<!--\n"
        "  SELF-CONTAINED auto training prompt: the snapshot is embedded below, so no\n"
        "  fetching is needed. Paste the WHOLE file into a fresh chatbot session.\n"
        "  Generated from AUTO_PROMPT.md + snapshot/ by gen_auto_prompt.py — do not edit\n"
        "  by hand. Refreshed with the snapshot; the embedded map is a point-in-time copy.\n"
        "-->\n\n"
    )
    return header + src.rstrip() + "\n\n" + _snapshot_block()


def main() -> None:
    open("AUTO_PROMPT_BUNDLED.md", "w", encoding="utf-8").write(build_bundled())


if __name__ == "__main__":
    main()
