#!/usr/bin/env python3
"""Generate snapshot/index.md — ONE combined coverage map across all four nodes.

The auto trainer needs to read the brain's coverage to find a real gap. Fetching
four separate node files is four requests (more truncation/rate-limit exposure);
this concatenates them into a single small file the prompt can fetch in one shot.

Regenerated by the export workflow whenever the per-node snapshots refresh, so it
never goes stale. Pure standard library. Run from the repo root.
"""

from __future__ import annotations

import os

NODES = ["tension", "memory", "ideas", "creativity"]  # tension first: richest for gaps


def build() -> str:
    out = [
        "# Collective snapshot — combined coverage map",
        "",
        "One line per entry the brain already holds, across all four nodes. A"
        " training-mode gap must come from something dangling here — an open"
        " `tension` fork, a sparsely covered area, an idea with no follow-up.",
        "",
    ]
    for node in NODES:
        path = os.path.join("snapshot", node, "index.md")
        if not os.path.exists(path):
            continue
        body = [
            l for l in open(path, encoding="utf-8").read().splitlines()
            if l.strip() and not l.startswith("# collective index")
        ]
        out.append(f"## {node} ({len(body)} entries)")
        out.extend(body)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    open(os.path.join("snapshot", "index.md"), "w", encoding="utf-8").write(build())


if __name__ == "__main__":
    main()
